version: "3.9"
services:
  fedisearch-elasticsearch:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fedisearch-elastic.rule=Host(`elastic.${FEDISEARCH_DOMAIN}`)"
      - "traefik.http.routers.fedisearch-elastic.entrypoints=https"
      - "traefik.http.routers.fedisearch-elastic.tls=true"
      - "traefik.http.routers.fedisearch-elastic.tls.certresolver=local"
      - "traefik.http.routers.fedisearch-elastic.tls.domains[0].main=elastic.${FEDISEARCH_DOMAIN}"
      - "traefik.http.services.fedisearch-elasticsearch.loadbalancer.server.port=9200"
  fedisearch-storage:
    image: skorpil/fedistore:dev
    build:
      target: dev
    labels:
      - "traefik.http.routers.fedisearch-storage.tls.certresolver=local"
    volumes:
      - ./build/fedistore/application:/srv

  fedisearch-crawler:
    image: skorpil/fedicrawl:dev
    build:
      target: dev
    volumes:
      - ./build/fedicrawl/application:/srv

  fedisearch-searcher:
    image: skorpil/fedisearch:dev
    build:
      target: dev
    labels:
      - "traefik.http.routers.fedisearch-searcher.tls.certresolver=local"
    volumes:
      - ./build/fedisearch/application:/srv

