version: "3.9"
services:
  fedisearch-elasticsearch:
    environment:
      - xpack.security.enrollment.enabled=true
    ports:
      - 9200:9200

  fedisearch-storage:
    image: skorpil/fedistore:dev
    build:
      target: dev
    ports:
      - 4000:3000
    volumes:
      - ./build/fedistore/application:/srv

  fedisearch-crawler:
    image: skorpil/fedicrawl:dev
    build:
      target: dev
    volumes:
      - ./build/fedicrawl/application:/srv

  fedisearch-searcher:
    image: skorpil/fedisearch:dev
    build:
      target: dev
    ports:
        - 3000:3000
    volumes:
      - ./build/fedisearch/application:/srv
#  fedisearch-kibana:
#    image: kibana:8.4.1
#    environment:
#      ELASTICSEARCH_HOSTS: '["http://elastic:${FEDISEARCH_ELASTIC_PASSWORD}@fedisearch-elasticsearch:9200"]'
#    networks:
#      fedisearch:
#        aliases:
#          - kibana
#    ports:
#      - 5601:5601
